# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hans/git/MichouChessGuiwxW

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hans/git/MichouChessGuiwxW

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hans/git/MichouChessGuiwxW/CMakeFiles /Users/hans/git/MichouChessGuiwxW//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hans/git/MichouChessGuiwxW/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MichouChessGuiwxW

# Build rule for target.
MichouChessGuiwxW: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MichouChessGuiwxW
.PHONY : MichouChessGuiwxW

# fast build rule for target.
MichouChessGuiwxW/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/build
.PHONY : MichouChessGuiwxW/fast

Labguage.o: Labguage.cpp.o
.PHONY : Labguage.o

# target to build an object file
Labguage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/Labguage.cpp.o
.PHONY : Labguage.cpp.o

Labguage.i: Labguage.cpp.i
.PHONY : Labguage.i

# target to preprocess a source file
Labguage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/Labguage.cpp.i
.PHONY : Labguage.cpp.i

Labguage.s: Labguage.cpp.s
.PHONY : Labguage.s

# target to generate assembly for a file
Labguage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/Labguage.cpp.s
.PHONY : Labguage.cpp.s

MainGui.o: MainGui.cpp.o
.PHONY : MainGui.o

# target to build an object file
MainGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/MainGui.cpp.o
.PHONY : MainGui.cpp.o

MainGui.i: MainGui.cpp.i
.PHONY : MainGui.i

# target to preprocess a source file
MainGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/MainGui.cpp.i
.PHONY : MainGui.cpp.i

MainGui.s: MainGui.cpp.s
.PHONY : MainGui.s

# target to generate assembly for a file
MainGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/MainGui.cpp.s
.PHONY : MainGui.cpp.s

MichouApp.o: MichouApp.cpp.o
.PHONY : MichouApp.o

# target to build an object file
MichouApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/MichouApp.cpp.o
.PHONY : MichouApp.cpp.o

MichouApp.i: MichouApp.cpp.i
.PHONY : MichouApp.i

# target to preprocess a source file
MichouApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/MichouApp.cpp.i
.PHONY : MichouApp.cpp.i

MichouApp.s: MichouApp.cpp.s
.PHONY : MichouApp.s

# target to generate assembly for a file
MichouApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/MichouApp.cpp.s
.PHONY : MichouApp.cpp.s

Schachbrett.o: Schachbrett.cpp.o
.PHONY : Schachbrett.o

# target to build an object file
Schachbrett.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/Schachbrett.cpp.o
.PHONY : Schachbrett.cpp.o

Schachbrett.i: Schachbrett.cpp.i
.PHONY : Schachbrett.i

# target to preprocess a source file
Schachbrett.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/Schachbrett.cpp.i
.PHONY : Schachbrett.cpp.i

Schachbrett.s: Schachbrett.cpp.s
.PHONY : Schachbrett.s

# target to generate assembly for a file
Schachbrett.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/Schachbrett.cpp.s
.PHONY : Schachbrett.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MichouChessGuiwxW.dir/build.make CMakeFiles/MichouChessGuiwxW.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MichouChessGuiwxW"
	@echo "... Labguage.o"
	@echo "... Labguage.i"
	@echo "... Labguage.s"
	@echo "... MainGui.o"
	@echo "... MainGui.i"
	@echo "... MainGui.s"
	@echo "... MichouApp.o"
	@echo "... MichouApp.i"
	@echo "... MichouApp.s"
	@echo "... Schachbrett.o"
	@echo "... Schachbrett.i"
	@echo "... Schachbrett.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

